name: epic:
description: Tracking issue (epic) that has several subtasks associated with it. Used for tracking larger issues or projects that can be broken down into several tasks.
title: "[epic]: "
labels: ["epic"]
body:
- type: checkboxes
  attributes: 
    label: Does a similar epic exist already?
    description: Verify that a similar epic does not exist within this repository.
    options:
    - label: Yes
      required: true
- type: textarea
  attributes:
    label: Sub-Tasks
    description: |
      List sub-tasks as checkboxes to this epic and tie them to open issues/PRs as they are created.
        - [ ] Example Sub-Task (1)
        - [ ] Example Sub-task (2)
    value: |
        - Sub-task (1)
        - Sub-task (2)
    render: markdown
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional Comments
    description: |
      Add any links, references, and screenshots that might help as well as any additional information that this template did not cover.
      
      Tip: Files can be attached by clicking this area to highlight it and then drag / drop.
  validations:
    required: false