# this machine readable TOML file defines the common parameters between all tools in this repo.
# It generally contains all the baselined details of the instrument that always apply.

[Pupils]  
aper_clear_OD = '5m' # Outer diameter of clear aperture on M1
m1_psd_B = 3.0

[sim_settings]  # settings for simulation tool
npix = 4096 # number of pixels per frame
beamrad = 0.4 # beam radius
